import {useEffect} from 'react'; import gsap from 'gsap'; import {ArrowUpRight,Calendar,Menu,Code2,BriefcaseBusiness} from 'lucide-react'; import ThroneScene from './ThroneScene';

export default function App(){useEffect(()=>{gsap.fromTo('.reveal',{y:42,opacity:0},{y:0,opacity:1,duration:1,stagger:.1,ease:'power4.out',delay:.15});gsap.fromTo('.throne-3d-shell',{scale:.94,opacity:0},{scale:1,opacity:1,duration:1.4,ease:'power3.out'});},[]);
return <main><div className="grain"/>
<nav><a className="brand" href="#home">ABHIJIT<span> PORTFOLIO</span></a><div className="navlinks"><a href="#about">About</a><a href="#projects">Projects</a><a href="#skills">Skills</a><a href="#contact">Contact</a></div><button className="menu" aria-label="Open menu"><Menu size={20}/></button></nav>

<section id="home" className="hero"><div className="hero-copy"><p className="eyebrow reveal"><Code2 size={14}/> ENGINEERING · CODE · AI · DESIGN</p><h1 className="blood reveal">BUILD<br/><span>YOUR</span><br/>WORLD.</h1><p className="lead reveal">Electrical engineering student who learns by building — exploring software, AI, design, hardware concepts and hackathons.</p><div className="actions reveal"><a className="primary" href="#projects">Explore my work <ArrowUpRight size={17}/></a><a className="secondary" href="#about">Discover me</a></div></div><div className="hero-art"><ThroneScene/></div></section>

<section id="about" className="story"><div><p className="eyebrow">THE ABHIJIT CODE</p><h2 className="blood small-blood">LEARN.<br/>BUILD.<br/>EVOLVE.</h2></div><div className="story-copy"><p>I’m Abhijit Singha, a first-year B.Tech Electrical & Electronics Engineering student at SVIST under MAKAUT.</p><p>I work across software, AI fundamentals, UI/UX, creative tools and engineering ideas, with a practical project-first approach.</p><div className="facts"><span>EEE · SVIST · MAKAUT</span><span>PYTHON · AI · GITHUB</span><span>KOLKATA · INDIA</span></div></div></section>

<section id="projects" className="services"><div className="section-head"><p className="eyebrow">SELECTED PROJECTS</p><span>01 — 03</span></div><div className="service-grid"><article><span>01</span><h3>APEXSTORE</h3><p>Interactive gaming marketplace with product discovery, detail views and modern UI.</p><a href="https://abhijitbot277.github.io/apexstore/" target="_blank" rel="noreferrer"><ArrowUpRight/></a></article><article><span>02</span><h3>AIR SENTINAL</h3><p>H₂S safety wristband concept with AI-assisted reading and connected worker monitoring.</p><a href="#contact"><ArrowUpRight/></a></article><article><span>03</span><h3>GREEN REVIVE</h3><p>Clean-tech concept for plastic identification using modulated NIR sensing and signal processing.</p><a href="#contact"><ArrowUpRight/></a></article><article><span>04</span><h3>MORE IN BUILD</h3><p>Experiments across web development, AI-assisted tools, design and engineering.</p><a href="https://github.com/Abhijitbot277" target="_blank" rel="noreferrer"><ArrowUpRight/></a></article></div></section>

<section id="skills" className="skills"><div><p className="eyebrow">TOOLKIT</p><h2 className="blood small-blood">CODE.<br/>CREATE.<br/>SOLVE.</h2></div><div className="skill-grid"><span>Python</span><span>AI Fundamentals</span><span>Git & GitHub</span><span>HTML / CSS / JS</span><span>UI / UX</span><span>Canva</span><span>Video Editing</span><span>MS Word / Excel</span><span>Communication</span><span>Public Speaking</span></div></section>

<section id="contact" className="booking"><div><p className="eyebrow">LET’S BUILD</p><h2 className="blood">MAKE<br/>IT<br/>REAL.</h2></div><div className="contact-actions"><a className="primary large" href="https://github.com/Abhijitbot277" target="_blank" rel="noreferrer"><BriefcaseBusiness size={18}/> GitHub</a><a className="primary large" href="mailto:abhijitsingha@example.com"><Calendar size={18}/> Contact me</a></div></section>
<footer><span>© 2026 ABHIJIT SINGHA</span><span>EEE · BUILDER · INDIA</span></footer></main>}